/// Flutter icons IconSet
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  IconSet
///      fonts:
///       - asset: fonts/IconSet.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class IconSet {
  IconSet._();

  static const _kFontFam = 'IconSet';
  static const String? _kFontPkg = null;

  static const IconData npm = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
